# Generated by Django 3.2.8 on 2021-11-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comitee',
            fields=[
                ('comitee_id', models.AutoField(primary_key=True, serialize=False)),
                ('comitee_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'comitee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('abreviation', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_reported', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('age', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('date_notified', models.DateField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('experiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('experiment_description', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField()),
                ('protocol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'experiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentMoleculeComposition',
            fields=[
                ('exp_mol_comp_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'experiment_molecule_composition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentSymptomRegister',
            fields=[
                ('exp_symptom_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('counter', models.IntegerField()),
            ],
            options={
                'db_table': 'experiment_symptom_register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('laboratory_id', models.AutoField(primary_key=True, serialize=False)),
                ('laboratory_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'laboratory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('molecule_id', models.AutoField(primary_key=True, serialize=False)),
                ('molecule_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'molecule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=30)),
                ('person_email', models.CharField(max_length=50)),
                ('pd', models.CharField(max_length=300)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_recieved', models.DateField()),
                ('date_registered', models.DateField()),
                ('effect_patient', models.CharField(blank=True, max_length=256, null=True)),
                ('effect_medicine', models.CharField(blank=True, max_length=256, null=True)),
                ('still_open', models.BooleanField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rolee',
            fields=[
                ('rolee_id', models.AutoField(primary_key=True, serialize=False)),
                ('rolee_name', models.CharField(max_length=30)),
                ('rolee_description', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'rolee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Susars',
            fields=[
                ('susars_id', models.AutoField(primary_key=True, serialize=False)),
                ('assesment_level', models.IntegerField()),
            ],
            options={
                'db_table': 'susars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('symptom_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_title', models.CharField(max_length=380)),
                ('symptom_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'symptom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomEventRegister',
            fields=[
                ('symp_event_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'symptom_event_register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('time_period_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'time_period',
                'managed': False,
            },
        ),
    ]
