# Generated by Django 3.2.9 on 2021-12-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anomaly_detection_api', '0002_auto_20211205_2327'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timeperiod',
            table='time_period',
        ),
    ]
